'use strict';
const $=s=>document.querySelector(s),make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
const rate=()=>Number($('#speed').value);
const posterObserver=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(isIntersecting&&target.dataset.src){target.src=target.dataset.src;posterObserver.unobserve(target)}}),{rootMargin:'220px'});
const heroCases=[W2M.cases[1],W2M.cases[0],W2M.cases[6]];
heroCases.forEach(c=>c.streams.forEach(s=>{const tile=make('div','hero-tile'),v=make('video');v.poster=s.poster;v.dataset.src=s.file;v.muted=true;v.loop=true;v.playsInline=true;v.preload='none';v.tabIndex=-1;tile.append(v);$('#hero-mosaic').append(tile)}));
let coverPlaying=false;
const coverButton=$('#hero-toggle');
function pauseCover(){for(const v of $('#hero-mosaic').querySelectorAll('video'))v.pause();coverPlaying=false;coverButton.textContent='Play cover';}
coverButton.addEventListener('click',async()=>{if(coverPlaying){pauseCover();return}try{await Promise.all([...$('#hero-mosaic').querySelectorAll('video')].map(v=>{if(!v.src)v.src=v.dataset.src;return v.play()}));coverPlaying=true;coverButton.textContent='Pause cover';}catch{pauseCover();coverButton.textContent='Retry cover';}});
new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)pauseCover()},{threshold:.05}).observe($('#cover'));
function watch(root,button){const update=()=>{const vs=[...root.querySelectorAll('video')];const finished=vs.every(v=>v.ended||(Number.isFinite(v.duration)&&v.currentTime>=v.duration-.01));const playing=vs.every(v=>!v.paused||v.ended)&&!finished;button.disabled=playing;button.textContent=playing?'Playing pair':vs.some(v=>v.currentTime>.025)&&!finished?'Resume pair':'Play pair';};for(const event of ['play','pause','ended','seeking','seeked','timeupdate'])root.addEventListener(event,update,true);update();}
function card(c,i){const article=make('article','demo-card'),pair=make('div','demo-pair');for(const s of c.streams){const fig=make('figure'),v=make('video');v.controls=true;v.muted=true;v.playsInline=true;v.preload='none';v.dataset.src=s.file;v.poster=s.poster;v.setAttribute('aria-label',c.title+' — '+s.label);v.addEventListener('loadedmetadata',()=>v.playbackRate=rate());posterObserver.observe(v);fig.append(v,make('figcaption','',s.label));pair.append(fig)}article.append(pair);const copy=make('div','card-copy'),top=make('div','card-top');top.append(make('span','case-number',String(i+1).padStart(2,'0')+' / '+c.category.toUpperCase()));copy.append(top,make('h3','',c.title));let prompt=c.displayPrompt||c.prompt;const p=make('p','',prompt);p.title=prompt;copy.append(p);const controls=make('div','pair-actions'),play=make('button','','Play pair'),pause=make('button','','Pause pair');play.type=pause.type='button';play.addEventListener('click',()=>{pauseCover();$('#overview-video').pause();linkPlayback(article).resume()});pause.addEventListener('click',()=>linkPlayback(article).pause());controls.append(play,pause);copy.append(controls);article.append(copy);linkPlayback(article);watch(article,play);return article;}
function gallery(category){const root=$('#demo-grid');for(const v of root.querySelectorAll('video')){v.pause();posterObserver.unobserve(v)}root.replaceChildren(...W2M.cases.filter(c=>c.category===category).map(card));root.setAttribute('aria-labelledby','tab-'+category);document.querySelectorAll('[role=tab]').forEach(b=>{const active=b.dataset.category===category;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});}
const tabs=[...document.querySelectorAll('[role=tab]')];tabs.forEach((b,i)=>{b.addEventListener('click',()=>gallery(b.dataset.category));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!=null){e.preventDefault();tabs[next].focus();gallery(tabs[next].dataset.category);}})});gallery('interaction');
$('#speed').addEventListener('change',()=>$('#demo-grid').querySelectorAll('video').forEach(v=>v.playbackRate=rate()));
$('#overview-video').addEventListener('play',()=>{pauseCover();$('#demo-grid').querySelectorAll('video').forEach(v=>v.pause())});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseCover();document.querySelectorAll('video').forEach(v=>v.pause())}});
$('#copy-citation').addEventListener('click',async()=>{const text=$('#bibtex').textContent;try{await navigator.clipboard.writeText(text);$('#copy-status').textContent='Citation copied.';$('#copy-citation').textContent='Copied';setTimeout(()=>$('#copy-citation').textContent='Copy BibTeX',2000);}catch{const range=document.createRange();range.selectNodeContents($('#bibtex'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);$('#copy-status').textContent='Citation selected. Press Ctrl+C or Command+C to copy.';}});
const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)document.querySelectorAll('.nav-links a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}),{rootMargin:'-10% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(s=>navObserver.observe(s));
